---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: putstatus
  name: marketplace-be-putstatus
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: putstatus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: putstatus
    spec:
      containers:
      - image: image
        name: putstatus
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "25m"