apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: putstatus
  name: marketplace-be-putstatus
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: putstatus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: putstatus
    spec:
      containers:
      - image: 192.168.110.135:5000/putstatus:2d0d7639
        name: putstatus
        resources:
          limits:
            cpu: 25m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
