apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: putstatus
  name: marketplace-be-putstatus
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: putstatus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: putstatus
    spec:
      containers:
      - image: 192.168.110.135:5000/putstatus:710
        name: putstatus
